;; SPDX-License-Identifier: PMPL-1.0-or-later
(meta (metadata (version "0.2.0") (last-updated "2026-02-14"))
  (project-info
    (type "mobile-app")
    (languages (rust idris2 zig))
    (license "PMPL-1.0-or-later")
    (author "Jonathan D.A. Jewell (hyperpolymath) <jonathan.jewell@open.ac.uk>")
    (framework "dioxus-0.7")
    (platforms (ios android desktop)))
  (architecture-decisions
    (adr "ADR-001" (title "Dioxus for mobile UI") (status "accepted")
      (decision "Use Dioxus 0.7+ — pure Rust, React-like, mobile-native"))
    (adr "ADR-002" (title "age for encryption at rest") (status "accepted")
      (decision "Use age crate with X25519 passphrase-based key derivation"))
    (adr "ADR-003" (title "IPP server on port 631") (status "accepted")
      (decision "Phone as network printer via raw TCP IPP + mDNS advertisement"))
    (adr "ADR-004" (title "Pure-Rust OCR via ocrs") (status "accepted")
      (decision "No C deps — ocrs ONNX-based pure Rust neural text recognition"))
    (adr "ADR-005" (title "SQLite for persistence") (status "accepted")
      (decision "rusqlite bundled for job queue + audit trail — survives app restart"))
    (adr "ADR-006" (title "Bridge.idr for platform FFI safety") (status "accepted")
      (decision "Extend Idris2 ABI with Bridge.idr proving toll-free bridging, keychain semantics, thread requirements, JNI invariants, and opaque handle safety"))
    (adr "ADR-007" (title "Content-addressed document storage") (status "accepted")
      (decision "Store received documents by SHA-256 hash — deduplication, integrity verification, simple retrieval")))
  (development-practices
    (unsafe-policy "Every unsafe block requires // SAFETY: comment referencing ABI proof")
    (banned-patterns ("believe_me" "Admitted" "unsafePerformIO" "transmute"))
    (testing "cargo test --workspace — 61 unit tests, clippy zero warnings")
    (security-scanning "panic-attack assail . — 10 weak points, 0 critical")))
